name: Build, Slim and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: johnermac/noumenon

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            --target runtime \
            -t $IMAGE_NAME:latest \
            .

      # -----------------------------
      # Slim the image
      # -----------------------------
      - name: Slim Docker image using DockerSlim container
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $(pwd):/workspace \
            dslim/slim:latest \
            build \
            --target $IMAGE_NAME:latest \
            --tag $IMAGE_NAME:slimmed \
            --include-shell \
            --include-bin bundle \
            --include-bin ruby \
            --http-probe=false

      # -----------------------------
      # Push images
      # -----------------------------
      - name: Push latest image
        run: docker push $IMAGE_NAME:latest

      - name: Push slimmed image
        run: docker push $IMAGE_NAME:slimmed
